Include scripting.h for DictionaryFree
The function `DictionaryFree` has been moved to `scripting.h` in commit
2b039c0b47595b1d760ff2034d457c243017351e.

This commit prevents the following warning

```
fontview.c: In function 'FontView_Free':
fontview.c:7567:5: warning: implicit declaration of function 'DictionaryFree'
                   [-Wimplicit-function-declaration]
     DictionaryFree(fv->b.fontvars);
```